options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("dplyr")
install.packages("data.table")
install.packages("jsonlite")
install.packages("lubridate")
install.packages("purrr")
install.packages("arrow")
