install.packages("dplyr", dependencies = TRUE)
install.packages("data.table", dependencies = TRUE)
install.packages("jsonlite", dependencies = TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("purrr", dependencies = TRUE)
