options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("tidyverse")
install.packages("data.table")
install.packages("jsonlite")
install.packages("lubridate")
install.packages("purrr")
install.packages("arrow")
install.packages("fixest")
install.packages("eventstudyr")
