Import('*')

target = [
    '#output/analysis/figure_adl_gap_refi_hazard/figure_adl_gap_refi_hazard.png'
]

source = [
    '#source/analysis/figure_adl_gap_refi_hazard/figure_adl_gap_refi_hazard.R',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.R(target, source)

target = [
    '#output/analysis/figure_cash_out_share/figure_cash_out_share.png'
]

source = [
    '#source/analysis/figure_cash_out_share/figure_cash_out_share.R',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.R(target, source)

target = [
    '#output/analysis/figure_rate_gap_at_exit/figure_rate_gap_at_exit_adjusted.png',
    '#output/analysis/figure_rate_gap_at_exit/figure_rate_gap_at_exit.png'
]

source = [
    '#source/analysis/figure_rate_gap_at_exit/figure_rate_gap_at_exit.R',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.R(target, source)

target = [
    '#output/analysis/figure_rate_gap_refi_hazard/figure_rate_gap_refi_hazard.png'
]

source = [
    '#source/analysis/figure_rate_gap_refi_hazard/figure_rate_gap_refi_hazard.R',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.R(target, source)

target = [
    '#output/analysis/figure_refi_delay/figure_refi_delay.png'
]

source = [
    '#source/analysis/figure_refi_delay/figure_refi_delay.R',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.R(target, source)

target = [
    '#output/analysis/figure_refi_delay/autofill_mean_refi_delay.tex'
]

source = [
    '#source/analysis/figure_refi_delay/autofill_refi_delay.py',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet'
]

env.Python(target, source)


helpers = [
    '#source/lib/parameters.json'
]

source = [
    '#source/analysis/table_savings/table_savings.py',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high.parquet',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_medium.parquet',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_low.parquet',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_high_refi_eligible.parquet',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_medium_refi_eligible.parquet',
    '#datastore/output/derived/fannie_mae/sflp_sample_processed_low_refi_eligible.parquet'
] + helpers

target = [
    '#output/analysis/table_savings/table_savings.txt'
]

env.Python(target, source)

