Import('*')

helpers = [
    '#source/lib/helpers/plot.py'
]

source = [
    '#source/analysis/plot_elasticities_refi_move.py',
    '#output/derived/sce/sce_housing.csv',
    '#output/derived/sce/sce_credit.csv',
    '#output/derived/mortgage_rates/mortgage30us.csv'
] + helpers

target = [
    '#output/analysis/elasticity_sell_home.png',
    '#output/analysis/elasticity_refi.png'
]

env.Python(target, source)


